import Link from 'next/link';
import DragonQuiz from '@/components/DragonQuiz';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { Faq } from '@/components/Faq';
import { pageMetadata } from '@/lib/metadata';

export const metadata = pageMetadata('Threshing Day Game Fan Quiz — Find Your Dragon', 'Try the original Threshing Day Game fan quiz: eight questions, six dragon affinities, and a result card to save. Independent from official Dragonkind.', '/fan-quiz/');
export default function QuizPage() {
  return <main id="main-content"><div className="container"><Breadcrumbs items={[{ label: 'Fan dragon quiz', href: '/fan-quiz/' }]} /></div><header className="tool-heading container"><span className="eyebrow">ORIGINAL FAN QUIZ · ABOUT 3 MINUTES</span><h1>Threshing Day Game fan quiz.</h1><p>Which dragon would choose you? Follow your instincts through eight moments at the edge of the unknown and discover your dragon affinity.</p></header><section className="container tool-surface" aria-label="Interactive dragon quiz"><DragonQuiz /></section><section className="container section tool-explainer"><div><span className="eyebrow">YOUR STORY. OUR ORIGINAL RULES.</span><h2>A fan quiz,<br />with its own imagination.</h2><p>This is an original personality quiz, not the official Dragonkind game. Your answers are scored consistently across six affinities. The same completed answers produce the same result.</p><p>These personality meanings belong to our quiz. They do not describe Rebecca Yarros’s official selection algorithm, dragon rarity, or your chances of surviving Threshing.</p><Link className="text-link" href="/dragon-results/">Understand official dragon results</Link></div><Faq items={[{ question: 'Is this the official Threshing Day game?', answer: 'No. This is our original, unofficial dragon affinity quiz. The official Dragonkind experience is at dragonkind.com and uses its own account and rules.' }, { question: 'Can I retake the quiz?', answer: 'Yes. You can start again immediately and explore a different set of choices. There is no cooldown on this fan quiz.' }, { question: 'Where is my result saved?', answer: 'Your quiz progress and result are saved in this browser when local storage is available. We do not upload them or connect them to your official Dragonkind account.' }, { question: 'Will this quiz help me get a black dragon in Dragonkind?', answer: 'No. Our quiz uses independent personality scores. It cannot predict, choose, or change an official Dragonkind result.' }]} /></section></main>;
}
